name=ViraMediaWeb
version=1.0.1
author=Mostafa Mir Mousavi (ViraMedar)
maintainer=Mostafa MirMousavi (ViraMedar)
sentence=ESP8266/ESP32 web-based file manager and media server using LittleFS
paragraph=Lightweight embedded web system with file upload, delete, preview and direct access. Works as a mini CDN for ESP devices with web UI.
category=Communication
architectures=esp8266,esp32
url=https://github.com/admin3314/ViraMediaWeb
