name=ViraMediaWeb
version=1.0.0
author=Mostafa MirMousavi
maintainer=Mostafa MirMousavi
sentence=ESP8266/ESP32 Web File Manager & Media Server
paragraph=Lightweight embedded web system for ESP8266/ESP32 providing file upload, delete, preview, and direct file access using LittleFS. Acts as a mini CDN and web storage server for IoT applications.
category=Communication
url=https://github.com/admin3314/ViraMediaWeb
architectures=esp8266,esp32
